### ISSUE TITLE
Compile/Watch .scss in components folder

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-boilerplate#87]
## Expected behavior
Sass get's compiled if there's no underscore and it should trigger a build if there's no underscore

## Actual behavior
In case you include it in resources, it works when saving the entrypoint file.

## Steps to reproduce

  1. Checkout project and just use it.
  2. Create a scss file somewhere in `src/components/<componentname>/styles.scss`
  3. Run `npm start` check for a compiled file.

## Specifications
  - Biotope Version: 6
  - Node Version: 11
  - Operating System: Mac OS

**Comment by no-creative-name** [comment]
If I grasped it right, the problem is that we check if the "currentFile.dirname" contains the "componentsFolderName":

`
if (currentFile.dirname.indexOf(componentsFolderName) === 0)...
`

If you log "dirname" you can see that it only contains the direct folder, where the scss file is located. E.g. if there's a "main.scss" under "components/testComponent/", "dirname" is "testComponent".
Thus dirname does not contain "components" and the scss file doesn't get copied.

I'd gladly open up a PR with a fix, but I'm not aware of any possible parameters that contain the full path.

**Comment by jurekbarth** [comment]
Ah i guess it's fixed in Version 6 of biotope-build. Can you recheck and open a PR if it's still an issue?

**Comment by no-creative-name** [comment]
You're right, works fine with biotope-build 6.0.0.
